### PR TITLE
fix(farming-calc): farming calc + remove auto-refresh + must select deposit or liquidate

### LINKED ISSUE #149: Fields reset while on liquidation screen
Fields seem to occasionally reset to their defaults when working through the liquidation modal.

### LINKED ISSUE #150: You can unselelect both tabs on the position info & actions modal
Screen Shot 2020-09-07 at 10 42 06 AM

### LINKED ISSUE #153: Farming calc hard codes yUSD pool
Should update for eligible LM pools:
- yUSD-OCT
-uUSDrBTC-OCT

### LINKED ISSUE #154: Only show LM roll information during roll

### PR DESCRIPTION
**Pull request by nicholaspai**
Fixes #149 
Fixes #150 
Fixes #153 
Fixes #154

### CODE REVIEW

File: containers/Balancer.ts [hunk 1]
```diff
@@ -110,13 +110,15 @@ const useBalancer = () => {
...
+      const IS_YIELD_TOKEN = Object.keys(YIELD_TOKENS).includes(
+        tokenAddress.toLowerCase()
+      );
       setIsYieldToken(IS_YIELD_TOKEN);
       if (IS_YIELD_TOKEN) {
         setSelectedTokenAddress(tokenAddress.toLowerCase());
         setPoolTokenList([
-          YIELD_TOKENS[tokenAddress].token0.toLowerCase(),
-          YIELD_TOKENS[tokenAddress].token1.toLowerCase(),
+          YIELD_TOKENS[tokenAddress.toLowerCase()].token0.toLowerCase(),
```
Comment (chrismaree) [inline containers/Balancer.ts:120]: cleaner like this 👍

**Review by chrismaree — APPROVED** [review]
Looks good to me!

**Comment by chrismaree** [comment]
@nicholaspai I'm going to merge this in on your behalf as people are having issues with this in production and need to get the fix out.
