### PR TITLE
fix(yield-calculator) Add ren payouts + update method selector

### LINKED ISSUE #156: Add Ren LM rewards calculation

### LINKED ISSUE #157: Wrap/Unwrap & yield tabs should only show up on relevent contracts

### LINKED ISSUE #158: You can unselelect both tabs on the yield tab

### PR DESCRIPTION
**Pull request by chrismaree**
close #156 
close #157 
close #158

### CODE REVIEW

File: features/contract-state/Totals.tsx [hunk 1]
```diff
@@ -64,8 +64,19 @@ const Totals = () => {
     tokenAddress !== null &&
     provider !== null
   ) {
-    const prettyTotalCollateral = Number(totalCollateral).toLocaleString();
-    const prettyTotalTokens = Number(totalTokens).toLocaleString();
+    const prettyTotalCollateral = Number(totalCollateral).toLocaleString(
```
Comment (chrismaree) [inline features/contract-state/Totals.tsx:67]: this fixes a wrap with the number of ren tokens created.

before:
image

after:
image

File: pages/index.tsx [hunk 2]
```diff
@@ -45,14 +49,26 @@ export default function Index() {
   const [tabIndex, setTabIndex] = useState(0);
   const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
   const [selectedIndex, setSelectedIndex] = useState(0);
+  const { address: collAddress } = Collateral.useContainer();
+  const { contract: weth } = WethContract.useContainer();
+  const { isYieldToken } = Balancer.useContainer();
+  // setTabIndex(0);
+
+  const options = ["General Info", "Manage Position", "All Positions"];
```
Comment (chrismaree) [inline pages/index.tsx:57]: shown on all EMPS.

File: pages/index.tsx [hunk 3]
```diff
@@ -45,14 +49,26 @@ export default function Index() {
...
-    "Wrap/Unwrap WETH",
-    "yUSD Yield",
-  ];
+  if (weth && collAddress == weth.address) {
+    options.push("Wrap/Unwrap WETH");
+  }
+
+  // Update selected page if the user toggles between EMPs while selected on
+  // invalid pages (i.e on Wrap/Unwrap then moves to uUSDrBTC)
+  if (tabIndex > options.length - 1) {
```
Comment (chrismaree) [inline pages/index.tsx:69]: if selecting an invalid option then move to the General info tab

File: features/yield/FarmingCalculator.tsx [hunk 4]
```diff
@@ -167,33 +181,58 @@ const FarmingCalculator = () => {
 
   // Update yield amount whenever inputs change.
   useEffect(() => {
-    const updatedYield = calculateYield(
+    const updatedUmaYield = calculateYield(
       Number(yUSDAdded) || 0,
       Number(USDCAdded) || 0,
       Number(yUSDPrice) || 0,
       Number(poolLiquidity) || 0,
       Number(umaPrice) || 0,
```
Comment (nicholaspai) [inline features/yield/FarmingCalculator.tsx:189]: You should add `Number(renPrice) || 0` here and change the default value for `renPrice` back to ""

File: features/yield/FarmingCalculator.tsx [hunk 5]
```diff
@@ -60,15 +66,18 @@ const FarmingCalculator = () => {
     timeRemainingToFarmingRoll / 1000 / 60 / 60;
 
   // Yield inputs:
-  const [umaPrice, setUmaPrice] = useState<string>("");
+  const [umaPrice, setUmaPrice] = useState<number>(0);
```
Comment (nicholaspai) [inline features/yield/FarmingCalculator.tsx:69]: Why'd you change this?

File: features/yield/FarmingCalculator.tsx [hunk 6]
```diff
@@ -96,24 +106,24 @@ const FarmingCalculator = () => {
...
     ) {
       return null;
     }
 
     const totalValueAddedToPool = _USDCAdded + _yUSDPrice * _yUSDAdded;
     const fracLiquidityProvided = totalValueAddedToPool / _poolLiquidity;
-    const umaPaidPerWeek = fracLiquidityProvided * _weeklyPoolRewards;
-    const usdYieldPerWeek = umaPaidPerWeek * _umaPrice;
+    const tokensPaidPerWeek = fracLiquidityProvided * _weeklyPoolRewards;
+    const usdYieldPerWeek = tokensPaidPerWeek * _tokenPrice;
```
Comment (nicholaspai) [inline features/yield/FarmingCalculator.tsx:126]: This is a smart refactor to just change the `tokenPrice`

File: features/yield/FarmingCalculator.tsx (hunk 5 above)
Comment (chrismaree) [reply features/yield/FarmingCalculator.tsx]: I thought it would be more consistent but it's fine to leave it as strings. I've reverted it.

File: features/yield/FarmingCalculator.tsx [hunk 7]
```diff
@@ -133,10 +143,14 @@ const FarmingCalculator = () => {
...
 
     if (WEEKLY_UMA_REWARDS[tokenAddress.toLowerCase()]) {
-      // TODO: Display REN rewards as well
-      const _weeklyPoolRewards =
-        WEEKLY_UMA_REWARDS[tokenAddress.toLowerCase()].UMA;
-      setWeeklyPoolRewards(_weeklyPoolRewards.toString());
+      const selectedTokenRewards =
+        WEEKLY_UMA_REWARDS[tokenAddress.toLowerCase()];
+      setWeeklyUmaRewards(selectedTokenRewards.UMA.toString());
+      if (Object.keys(selectedTokenRewards).includes("REN")) {
```
Comment (nicholaspai) [inline features/yield/FarmingCalculator.tsx:149]: Don't love this hard coded solution but it works for now

Comment (chrismaree) [reply features/yield/FarmingCalculator.tsx:149]: ye, not ideal. we could generalize it but would need to re-build this whole component I think.

File: pages/index.tsx [hunk 8]
```diff
@@ -45,14 +49,26 @@ export default function Index() {
   const [tabIndex, setTabIndex] = useState(0);
   const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
   const [selectedIndex, setSelectedIndex] = useState(0);
+  const { address: collAddress } = Collateral.useContainer();
+  const { contract: weth } = WethContract.useContainer();
+  const { isYieldToken } = Balancer.useContainer();
+  // setTabIndex(0);
```
Comment (nicholaspai) [inline pages/index.tsx:55]: DId you mean to remove this comment?

File: features/yield/FarmingCalculator.tsx (hunk 5 above)
Comment (nicholaspai) [reply features/yield/FarmingCalculator.tsx]: Yeah actually more consistent to leave like the others as ""

**Review by nicholaspai — APPROVED** [review]
Quick solution, lgtm!
